# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/linux-64/bokeh-1.4.0-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/datashader-0.13.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/imageio-2.6.1-py36_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-base-3.3.4-py36hd391965_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numba-0.53.1-py36h1328434_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.19.5-py36hfc0c790_2.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/pandas-1.1.5-py36ha9443f7_0.conda
https://repo.anaconda.com/pkgs/main/linux-64/psutil-5.8.0-py36h27cfd23_1.conda
https://repo.anaconda.com/pkgs/main/linux-64/pytables-3.6.1-py36h71ec239_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scikit-learn-0.22.1-py36hd81dba3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/linux-64/scipy-1.3.1-py36he2b7bc3_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tqdm-4.64.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/umap-learn-0.3.10-py36_0.tar.bz2
