name: Python test 
run-name: python_test 
on: [pull_request]
jobs:
  Preamble:
    runs-on: self-hosted
    steps:
      - run: cd ~/Desktop/blech_clust
      - run: pwd
      - run: which python
      - run: conda info --envs
      - name: Set up repo
        uses: actions/checkout@v4
      - run: echo "${{ github.ref }} ${{ github.repository }}"
  Spike-Only:
    runs-on: self-hosted
    steps:
      - name: Set up repo
        uses: actions/checkout@v4
      - name: Prefect SPIKE only test
        shell: bash
        working-directory: /home/abuzarmahmood/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py -s 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi
  EMG-Only:
    runs-on: self-hosted
    steps:
      - name: Set up repo
        uses: actions/checkout@v4
      - name: Prefect EMG only test
        shell: bash
        working-directory: /home/abuzarmahmood/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py -e 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi
  Spike-EMG:
    runs-on: self-hosted
    steps:
      - name: Set up repo
        uses: actions/checkout@v4
      - name: Prefect SPIKE then EMG test
        shell: bash
        working-directory: /home/abuzarmahmood/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi

