name: Python test 
run-name: python_test 
on: [push]
jobs:
  Python-Test-Action:
    runs-on: self-hosted
    steps:
      - run: cd ~/Desktop/blech_clust
      - run: pwd
      - run: which python
      - run: conda info --envs
      - name: Run prefect tests
        working-directory: /home/abuzarmahmood/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py --all
