name: Python test 
run-name: python_test 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - run: cd ~/Desktop/blech_clust 
      - run: echo which python
      - run: python blech_exp_info.py
